      subroutine mndomkin()
        use atomid
        use atoms
        use mndo
        use charge

        implicit none

        integer :: i, j, l, elb

        integer trimtext
  
  10   format(i2, 8x, 3(F10.5,2x,i2,6x))
  20   format(3F12.7,F8.4)

        open(unit=mndo_in_unit, file=mndo_in)

c       Write input options
        call mndo_out_keys(mndo_in_unit)

c       Write header comments
        write(mndo_in_unit, *) "Generated by Tinker-MNDO interface."
        write(mndo_in_unit, *) "Finger crossed."

        do i=1, nqmatoms
          write(mndo_in_unit, 10) atomic(qmlist(i)), x(qmlist(i)), 1,
     &    y(qmlist(i)), 1, z(qmlist(i)), 1
        end do

        write(mndo_in_unit, *) ""

        do i=1, mndo_neline
          l = trimtext(mndo_eline(i))
          write(mndo_in_unit, *) mndo_eline(i)(:l)
        end do

        do i=1, n-nqmatoms
          write(mndo_in_unit, 20) x(mmlist(i)), y(mmlist(i)), 
     $    z(mmlist(i)), pchg(mmlist(i))
        end do

        close(mndo_in_unit)
      end
