      subroutine mndomkin()
        use atomid
        use atoms
        use mndo
        use charge

        implicit none

        integer :: i, j, l, elb
        logical :: isqm

        integer trimtext
  
  10   format(i2, 8x, 3(F10.5,2x,i2,6x))
  20   format(4F10.5)

        open(unit=mndo_in_unit, file=mndo_in)

        do i=1, mndot_oline
          l = trimtext(mndo_template(i))
          write(mndo_in_unit, *) mndo_template(i)(:l)
        end do
        write(mndo_in_unit, *) "Generated by Tinker-MNDO interface."
        write(mndo_in_unit, *) "Finger crossed."

        do i=1, nqmatoms
          write(mndo_in_unit, 10) atomic(qmlist(i)), x(qmlist(i)), 1,
     &    y(qmlist(i)), 1, z(qmlist(i)), 1
        end do

        write(mndo_in_unit, *) ""

        elb = mndot_oline + 2 + nqmatoms + 1
        do i=1, mndot_eline
          l = trimtext(mndo_template(i+elb))
          write(mndo_in_unit, *) mndo_template(i+elb)(:l)
        end do

        do i=1, n
          isqm = .false.
          do j=1, nqmatoms
            if(i .eq. qmlist(j)) isqm = .true.
          end do
          if (.not. isqm) then
            write(mndo_in_unit, 20) x(i), y(i), z(i), pchg(i)
          end if 
        end do

        close(mndo_in_unit)
      end
